title: "Alexey Elagin"
#email: your-email@example.com
description: >- 
  Welcome to my homepage!
baseurl: "" 
url: "https://AlexeyElagin.github.io"  
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-include-cache

# Author info (for the left sidebar)
author:
 # name   : "Alexey Elagin"
  avatar : "/assets/me squared.jpg"
  bio    : "Turning coffee into theorems"
 #location: "planet Earth"

show_author_profile: true

css: ["assets/css/custom.css"]
